 version: 0.0
 os: linux
 files:
   - source: /
     destination: /home/ubuntu/sonar-server
 permissions:
   - object: /home/ubuntu
     owner: ubuntu
     group: ubuntu
     type:
       - directory
       - file
